# Copyright (c) 2022 StreamNative, Inc.. All Rights Reserved.

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: pulsar-resources-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PulsarConnection is the Schema for the pulsarconnections API
      displayName: Pulsar Connection
      kind: PulsarConnection
      name: pulsarconnections.resource.streamnative.io
      version: v1alpha1
    - description: PulsarNamespace is the Schema for the pulsarnamespaces API
      displayName: Pulsar Namespace
      kind: PulsarNamespace
      name: pulsarnamespaces.resource.streamnative.io
      version: v1alpha1
    - description: PulsarPermission is the Schema for the pulsarpermissions API
      displayName: Pulsar Permission
      kind: PulsarPermission
      name: pulsarpermissions.resource.streamnative.io
      version: v1alpha1
    - description: PulsarTenant is the Schema for the pulsartenants API
      displayName: Pulsar Tenant
      kind: PulsarTenant
      name: pulsartenants.resource.streamnative.io
      version: v1alpha1
    - description: PulsarTopic is the Schema for the pulsartopics API
      displayName: Pulsar Topic
      kind: PulsarTopic
      name: pulsartopics.resource.streamnative.io
      version: v1alpha1
  description: pulsar resources operator
  displayName: Pulsar Resources Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - resources
  - pulsar
  - streamnative
  links:
  - name: Pulsar Resources Operator
    url: https://pulsar-resources-operator.domain
  maintainers:
  - email: fswang@streamnative.io
    name: fswang
  maturity: alpha
  provider:
    name: StreamNative
    url: streamnative.io
  version: 0.0.0
