# Copyright 2022 StreamNative
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Append samples you want in your CSV to this file as resources ##
resources:
- resource_v1alpha1_pulsarconnection.yaml
- resource_v1alpha1_pulsarnamespace.yaml
- resource_v1alpha1_pulsartenant.yaml
- resource_v1alpha1_pulsartopic.yaml
- resource_v1alpha1_pulsarpermission.yaml
- resource_v1alpha1_pulsargeoreplication.yaml
- resource_v1alpha1_pulsarpackage.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
